old_versions/shorturl/shorturl/accounts/urls.py
from django.conf.urls import url

from .views import RegisterPageView


app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page': 'home:index'}, name='logout'),
    url(r'^register/$', RegisterPageView.as_view(), name='register')
]

old_versions/shorturl/shorturl/home/urls.py
from django.conf.urls import url

from .views import HomePageView


app_name = 'home'

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='index'),
]

old_versions/shorturl/shorturl/urls.py
from django.conf.urls import include, url
from django.contrib import admin


admin.autodiscover()

urlpatterns = [
    url(r'^$', include('shorturl.home.urls', namespace='home')),
    url(r'^accounts/',
        include('shorturl.accounts.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),
]

old_versions/shorturl/shorturl/accounts/models.py
from django.db import models

# Create your models here.

old_versions/shorturl/shorturl/home/models.py
from django.db import models

# Create your models here.

old_versions/shorturl/shorturl/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):

    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                'There is already a user with this email')

        return email

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()

        return user

old_versions/shorturl/shorturl/accounts/views.py
from django.views.generic import CreateView
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render
from django.conf import settings

from .forms import RegisterForm


class RegisterPageView(CreateView):

    template_name = 'accounts/register.html'
    form_class = RegisterForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.username, password=form.cleaned_data['password1']
            )
            login(request, user)
            return redirect('home:index')
        else:
            return render(request, self.template_name, {'form': form})

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'form': self.form_class})

    def get_context_data(self, **kwargs):
        context = super(RegisterPageView, self).get_context_data(**kwargs)
        return context

old_versions/shorturl/shorturl/home/views.py
from django.views.generic.base import TemplateView


class HomePageView(TemplateView):

    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        return context

old_versions/shorturl/shorturl/accounts/templates/accounts/login.html
{% extends 'base_template.html' %}


{% load staticfiles %}

{% block content %}
<section class="breadcrumb breadcrumb_bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="breadcrumb_iner text-center">
                    <div class="breadcrumb_iner_item">
                        <h2>SIGN IN & START SHARING</h2>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="breadcrumb_iner text-center">
                    <div class="breadcrumb_iner_item">
                      <form class="single_feature" method="post">
                          {% csrf_token %}
                          <fieldset>
                              {{ form.non_field_errors }}

                              {% for field in form %}
                              <div class="single_feature_part">
                                <h3>
                                  {{ field.label_tag }}
                                  {{ field }}
                                </h3>
                                <h4>
                                  {{ field.errors }}
                                </h4>
                              </div>
                              {% endfor %}

                              <div class="pure-controls">
                                  <button type="submit" class="button button-contactForm btn_1">Sign in</button>
                              </div>
                          </fieldset>
                          <p>
                              Don't have an account? <a href="{% url 'accounts:register' %}" title="">Sign up</a> <br />
                              Forget? <a href="" title="">Create a new password</a> <br />
                          </p>
                      </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

old_versions/shorturl/shorturl/accounts/templates/accounts/register.html
{% extends 'base_template.html' %}


{% load staticfiles %}

{% block content %}
<section class="breadcrumb breadcrumb_bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="breadcrumb_iner text-center">
                    <div class="breadcrumb_iner_item">
                        <h2>Create a free account</h2>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="breadcrumb_iner text-center">
                    <div class="breadcrumb_iner_item">
                      <form class="single_feature" method="post">
                          {% csrf_token %}
                          <fieldset>
                              {{ form.non_field_errors }}

                              {% for field in form %}
                              <div class="single_feature_part">
                                <h3>
                                  {{ field.label_tag }}
                                  {{ field }}
                                </h3>
                                <h4>
                                  {{ field.errors }}
                                </h4>
                              </div>
                              {% endfor %}

                              <div class="pure-controls">
                                  <button type="submit" class="button button-contactForm btn_1">Create Account</button>
                              </div>
                          </fieldset>
                          <p>
                              Alreade have an account? <a href="{% url 'accounts:login' %}" title="">Sign in</a> <br />
                          </p>
                      </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

old_versions/shorturl/shorturl/home/templates/base_template.html
{% load staticfiles %}

<!doctype html>
<html lang="zxx">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ecobit</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <!-- style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <!--::header part start::-->
    <header class="main_menu">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand main_logo" href="{% url 'home:index' %}"> <img src="{% static 'img/logo.png' %}" alt="logo"> </a>
                        <a class="navbar-brand single_page_logo" href="{% url 'home:index' %}"> <img src="{% static 'img/footer_logo.png' %}" alt="logo"> </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="menu_icon"></span>
                        </button>

                        <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Why ecobit?</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">features</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Pricing</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="# %}">Contact</a>
                                </li>
                            </ul>
                        </div>
                        {% if user.is_authenticated %}
                        <a href="{% url 'accounts:logout' %}" class="d-none d-sm-block btn_1">Logout</a>
                        {% else %}
                        <a href="{% url 'accounts:login' %}" class="d-none d-sm-block btn_1">Log in</a>
                        <a href="{% url 'accounts:register' %}" class="d-none d-sm-block btn_1">Sign up</a>
                        {% endif %}
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!--::Header part end::-->

    {% block content %}
    {% endblock %}

    <!--::footer_part start::-->
    <footer class="footer_part">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="copyright_text">
                        <P><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></P>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="footer_icon social_icon">
                        <ul class="list-unstyled">
                            <li><a href="#" class="single_social_icon"><i class="fab fa-facebook-f"></i></a></li>
                            <li><a href="#" class="single_social_icon"><i class="fab fa-twitter"></i></a></li>
                            <li><a href="#" class="single_social_icon"><i class="fas fa-globe"></i></a></li>
                            <li><a href="#" class="single_social_icon"><i class="fab fa-behance"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--::footer_part end::-->

    <!-- jquery plugins here-->
    <script src="{% static 'js/jquery-1.12.1.min.js' %}"></script>
    <!-- popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- easing js -->
    <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/swiper.min.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/masonry.pkgd.js' %}"></script>
    <!-- particles js -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <!-- slick js -->
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <!-- custom js -->
    <script src="{% static 'js/custom.js' %}"></script>
</body>

</html>

old_versions/shorturl/shorturl/home/templates/index.html
{% extends 'base_template.html' %}

{% load staticfiles %}

{% block content %}
    <!--::banner part start::-->
    <section class="banner_part">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-lg-5">
                    <div class="banner_img d-none d-lg-block">
                        <img src="{% static 'img/banner_img.png' %}" alt="">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="banner_text">
                        <div class="banner_text_iner">
                            <h1>Links that mean business</h1>
                            <p>Create and share trusted, powerful short links</p>
                            <a href="#" class="btn_2">Sign Up for Free</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <img src="{% static 'img/animate_icon/Ellipse_7.png' %}" alt="" class="feature_icon_1 custom-animation1">
        <img src="{% static 'img/animate_icon/Ellipse_8.png' %}" alt="" class="feature_icon_2 custom-animation2">
        <img src="{% static 'img/animate_icon/Ellipse_1.png' %}" alt="" class="feature_icon_3 custom-animation3">
        <img src="{% static 'img/animate_icon/Ellipse_2.png' %}" alt="" class="feature_icon_4 custom-animation4">
        <img src="{% static 'img/animate_icon/Ellipse_3.png' %}" alt="" class="feature_icon_5 custom-animation5">
        <img src="{% static 'img/animate_icon/Ellipse_4.png' %}" alt="" class="feature_icon_6 custom-animation6">
    </section>
    <!--::banner part start::-->

    <!--::shorten us part end::-->
    <section class="subscribe_part padding_bottom">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="subscribe_part_text text-center">
                        <div class="subscribe_form">
                            <form action="#">
                                <div class="form-row">
                                    <div class="col-sm-9">
                                        <input type="email" class="form-control" placeholder="shorten your link">
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="subscribe_btn">
                                            <div class="btn_2 d-block">Shorten</div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <img src="{% static 'img/animate_icon/Ellipse_5.png' %}" alt="" class="feature_icon_2 custom-animation2">
    </section>
    <!--::shorten us part end::-->

    <!--::use sasu part end::-->
    <section class="use_sasu padding_top">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-4 col-sm-6">
                    <div class="single_feature">
                        <div class="single_feature_part">
                            <img src="{% static 'img/icon/feature_icon_1.png' %}" alt="">
                            <h4>Fully Secured</h4>
                            <p>Made great fish shall beast, fourth land also Doesn
                                tree without lesser likeness he fruit of called gathering
                                day whose called were have </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <div class="single_feature">
                        <div class="single_feature_part">
                            <img src="{% static 'img/icon/feature_icon_2.png' %}" alt="">
                            <h4>Unique Design</h4>
                            <p>Made great fish shall beast, fourth land also Doesn tree
                                without lesser likeness he fruit of called gathering day whose
                                called were have </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <div class="single_feature">
                        <div class="single_feature_part">
                            <img src="{% static 'img/icon/feature_icon_3.png' %}" alt="">
                            <h4>A Volunteer</h4>
                            <p>Made great fish shall beast, fourth land also Doesn tree without
                                lesser likeness he fruit of called gathering day whose called were have </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <img src="{% static 'img/animate_icon/Ellipse_1.png' %}" alt="" class="feature_icon_1 custom-animation1">
    </section>
    <!--::use sasu part end::-->
{% endblock %}